apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-app-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-app-flask
  template:
    metadata:
      labels:
        app: mi-app-flask
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      automountServiceAccountToken: false
      containers:
      - name: mi-app-flask
        image: ghcr.io/alesisneros14/sisnerosalexis_practica_ci-cd:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"